---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: bazzite
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/bazzite
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: default-flatpaks
    notify: true
    system:
      install:
        - eu.betterbird.Betterbird
      remove:
        - org.gnome.eog
    user: {} # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
  
  - type: script
    scripts:
      - install_apps.sh
      - cachyos-kernel.sh

  - type: dnf
    repos:
      copr:
        enable:
          - bieszczaders/kernel-cachyos-lto
          - sneexy/zen-browser
    install:
      #allow-erasing: true
      packages:
        - kernel-cachyos-lto
        - kernel-cachyos-lto-modules
        - kernel-cachyos-lto-core
        - kernel-cachyos-lto-devel-matched
        - zen-browser
        - chezmoi
    remove:
      auto-remove: false
      packages:
        - kernel-core
        - kernel-modules
        - kernel-devel
        - kernel-headers

  - type: chezmoi
    repository: "https://github.com/ndowens/dotfiles.git"
    all-users: false
    file-conflict-policy: replace

  - type: systemd
    system:
      disabled:
        - tailscaled
    user:
      enabled:
        - chezmoi-init.service
        - chezmoi-update.timer
