---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: bazzite
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/bazzite
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: default-flatpaks
    notify: true
    system:
      install:
        - eu.betterbird.Betterbird
      remove:
        - org.gnome.eog
    user: {} # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
  
  - type: script
    scripts:
      - install_apps.sh
    snippets:
      - "setsebool -P domain_kernel_load_modules on"

  - type: dnf
    repos:
      copr:
        enable:
          - bieszczaders/kernel-cachyos-lto
          - lihaohong/chezmoi
    install:
        packages:
        - firefox
        - kernel-cachyos-lto
        - kernel-cachyos-lto-modules
        - kernel-cachyos-lto-core
        - kernel-cachyos-lto-devel-matched
        - zen-browser
        - google-noto-fonts-all
        - chezmoi
        - repo: copr:copr.fedorainfracloud.org:bieszczaders:kernel-cachyos-lto
          packages:
            - akmods
    remove:
      auto-remove: false
      packages:
        - kernel-core
        - kernel-modules
        - kernel-devel
        - kernel-headers

  - type: chezmoi
    repository: "https://github.com/ndowens/dotfiles.git"
    all-users: false
    file-conflict-policy: replace

  - type: systemd
    system:
      disabled:
        - tailscaled
      enabled:
        - podman.socket
        - libvirtd.service
    user:
      enabled:
        - chezmoi-init.service
        - chezmoi-update.timer