---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: bazzite
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      install:
        - eu.betterbird.Betterbird
      remove:
        - org.gnome.eog
    user: {} # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
  
  - type: script
    scripts:
      #- hyprland.sh
      - install_apps.sh
      - cachyos-kernel.sh

  - type: dnf
    repos:
      files:
        - https://copr.fedorainfracloud.org/coprs/bieszczaders/kernel-cachyos-lto/repo/fedora-42/bieszczaders-kernel-cachyos-lto-fedora-42.repo
        - https://copr.fedorainfracloud.org/coprs/sneexy/zen-browser/repo/fedora-42/sneexy-zen-browser-fedora-42.repo
      keys:
        - https://download.copr.fedorainfracloud.org/results/bieszczaders/kernel-cachyos-lto/pubkey.gpg
    install:
      - kernel-cachyos-lto
      - kernel-cachyos-lto-modules
      - kernel-cachyos-lto-core
      - kernel-cachyos-lto-devel-matched
      - zen-browser
    remove:
    allow-erasing: true
    packages:
      - kernel-core
      - kernel-modules
      - kernel-devel
      - kernel-headers
    replace:
      - from-repo: https://copr.fedorainfracloud.org/coprs/bieszczaders/kernel-cachyos-lto/repo/fedora-42/bieszczaders-kernel-cachyos-lto-fedora-42.repo
        packages:
          - akmods
